In [1]:
#Task 1: Unit Conversion Program
def convert_units(conversion_type, value):
    """
    Converts units based on the selected conversion type.

    Parameters:
    conversion_type (str): Type of conversion (m_to_ft, ft_to_m, kg_to_lbs, lbs_to_kg, l_to_gal, gal_to_l)
    value (float): Value to be converted

    Returns:
    float: Converted value
    """

    if conversion_type == "m_to_ft":
        return value * 3.28084
    elif conversion_type == "ft_to_m":
        return value / 3.28084
    elif conversion_type == "kg_to_lbs":
        return value * 2.20462
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462
    elif conversion_type == "l_to_gal":
        return value * 0.264172
    elif conversion_type == "gal_to_l":
        return value / 0.264172
    else:
        raise ValueError("Unsupported conversion type")


try:
    print("Choose Conversion Type:")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    choice = int(input("Enter your choice: "))
    value = float(input("Enter value to convert: "))

    conversions = {
        1: "m_to_ft",
        2: "ft_to_m",
        3: "kg_to_lbs",
        4: "lbs_to_kg",
        5: "l_to_gal",
        6: "gal_to_l"
    }

    result = convert_units(conversions[choice], value)
    print("Converted Value:", result)

except ValueError:
    print("Invalid input. Please enter numeric values.")
except KeyError:
    print("Invalid conversion choice.")

Choose Conversion Type:
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter your choice: 2
Enter value to convert: 800
Converted Value: 243.83999219712024


In [3]:
#Task 2: Mathematical Operations on List
def find_sum(numbers):
    """
    Returns the sum of numbers.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Returns the average of numbers.
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Returns the maximum number.
    """
    return max(numbers)


def find_min(numbers):
    """
    Returns the minimum number.
    """
    return min(numbers)


try:
    print("Select Operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = int(input("Enter choice: "))
    nums = list(map(float, input("Enter numbers separated by space: ").split()))

    if len(nums) == 0:
        raise ValueError("List cannot be empty")

    if choice == 1:
        print("Sum:", find_sum(nums))
    elif choice == 2:
        print("Average:", find_average(nums))
    elif choice == 3:
        print("Maximum:", find_max(nums))
    elif choice == 4:
        print("Minimum:", find_min(nums))
    else:
        print("Invalid choice")

except ValueError:
    print("Invalid input. Please enter numeric values.")

Select Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice: 1
Enter numbers separated by space: 23 45
Sum: 68.0


In [4]:
#Exercise on List Manipulation
def extract_every_other(lst):
    """Returns every other element starting from the first."""
    return lst[::2]


def get_sublist(lst, start, end):
    """Returns a sublist from start to end index inclusive."""
    return lst[start:end+1]


def reverse_list(lst):
    """Returns the reversed list using slicing."""
    return lst[::-1]


def remove_first_last(lst):
    """Removes first and last elements."""
    return lst[1:-1]


def get_first_n(lst, n):
    """Returns first n elements."""
    return lst[:n]


def get_last_n(lst, n):
    """Returns last n elements."""
    return lst[-n:]


def reverse_skip(lst):
    """Returns every second element in reverse starting from second last."""
    return lst[-2::-2]


# Example usage
lst = [1,2,3,4,5,6]

print("Every other:", extract_every_other(lst))
print("Sublist:", get_sublist(lst,2,4))
print("Reverse:", reverse_list(lst))
print("Remove first last:", remove_first_last(lst))
print("First n:", get_first_n(lst,3))
print("Last n:", get_last_n(lst,2))
print("Reverse skip:", reverse_skip(lst))

Every other: [1, 3, 5]
Sublist: [3, 4, 5]
Reverse: [6, 5, 4, 3, 2, 1]
Remove first last: [2, 3, 4, 5]
First n: [1, 2, 3]
Last n: [5, 6]
Reverse skip: [5, 3, 1]


In [5]:
#Exercise on Nested Lists
def flatten(lst):
    """
    Flattens a nested list into a single list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result


def access_nested_element(lst, indices):
    """
    Access element from nested list using indices.
    """
    for index in indices:
        lst = lst[index]
    return lst


def sum_nested(lst):
    """
    Returns sum of all elements in nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


def remove_element(lst, elem):
    """
    Removes all occurrences of element from nested list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result


def find_max(lst):
    """
    Finds maximum element in nested list.
    """
    flat = flatten(lst)
    return max(flat)


def count_occurrences(lst, elem):
    """
    Counts occurrences of an element in nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


def deep_flatten(lst):
    """
    Deeply flattens nested lists.
    """
    return flatten(lst)


def average_nested(lst):
    """
    Calculates average of nested list elements.
    """
    flat = flatten(lst)
    return sum(flat) / len(flat)


# Example usage
nested = [[1,2],[3,[4,5]],6]

print("Flatten:", flatten(nested))
print("Access element:", access_nested_element([[1,2,3],[4,5,6],[7,8,9]],[1,2]))
print("Sum nested:", sum_nested(nested))
print("Remove element:", remove_element([[1,2],[3,2],[4,5]],2))
print("Max nested:", find_max(nested))
print("Count occurrences:", count_occurrences([[1,2],[2,3],[2,4]],2))
print("Deep flatten:", deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))
print("Average nested:", average_nested([[1,2],[3,4],[5,6]]))

Flatten: [1, 2, 3, 4, 5, 6]
Access element: 6
Sum nested: 21
Remove element: [[1], [3], [4, 5]]
Max nested: 6
Count occurrences: 3
Deep flatten: [1, 2, 3, 4, 5, 6, 7, 8]
Average nested: 3.5


**Numpy**

In [6]:
pip install numpy

In [7]:
#Basic Vector and Matrix Operations with NumPy Problem 1: Array Creation
import numpy as np

# 1. Empty array 2x2
empty_array = np.empty((2,2))
print("Empty Array:\n", empty_array)

# 2. Ones array 4x2
ones_array = np.ones((4,2))
print("\nOnes Array:\n", ones_array)

# 3. Array filled with a specific value
full_array = np.full((3,3), 7)
print("\nFull Array:\n", full_array)

# 4. Zeros array with same shape
zeros_like_array = np.zeros_like(ones_array)
print("\nZeros Like Array:\n", zeros_like_array)

# 5. Ones array with same shape
ones_like_array = np.ones_like(zeros_like_array)
print("\nOnes Like Array:\n", ones_like_array)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("\nList to NumPy Array:\n", numpy_array)

Empty Array:
 [[1.05377699e-315 0.00000000e+000]
 [1.50594796e+161 1.14448783e+243]]

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones Like Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

List to NumPy Array:
 [1 2 3 4]


In [8]:
#Problem 2: Array Manipulation
# 1. Array from 10 to 49
arr = np.arange(10,50)
print("Array 10 to 49:\n", arr)

# 2. 3x3 matrix from 0 to 8
matrix = np.arange(9).reshape(3,3)
print("\n3x3 Matrix:\n", matrix)

# 3. Identity matrix
identity = np.eye(3)
print("\nIdentity Matrix:\n", identity)

# 4. Random array size 30 and mean
random_array = np.random.random(30)
print("\nRandom Array Mean:", random_array.mean())

# 5. 10x10 random array min and max
rand_matrix = np.random.random((10,10))
print("\nMin:", rand_matrix.min())
print("Max:", rand_matrix.max())

# 6. Zero array and replace 5th element
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nModified Array:\n", zero_array)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
print("\nReversed Array:\n", arr[::-1])

# 8. 2D array with border 1 and inside 0
border_array = np.ones((5,5))
border_array[1:-1,1:-1] = 0
print("\nBorder Array:\n", border_array)

# 9. Checkerboard pattern 8x8
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nCheckerboard Pattern:\n", checkerboard)

Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array Mean: 0.5200821402565979

Min: 0.00043457592619478014
Max: 0.9974629421431708

Modified Array:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed Array:
 [0 4 0 0 2 1]

Border Array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
#Problem 3: Array Operations
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1. Addition
print("x + y =\n", x + y)

# 2. Subtraction
print("\nx - y =\n", x - y)

# 3. Multiply array with integer
print("\nx * 3 =\n", x * 3)

# 4. Square of elements
print("\nSquare of x:\n", np.square(x))

# 5. Dot products
print("\nDot product v·w =", np.dot(v,w))
print("Dot product x·v =", np.dot(x,v))
print("Dot product x·y =\n", np.dot(x,y))

# 6. Concatenate arrays
print("\nConcatenate x and y (rows):")
print(np.concatenate((x,y), axis=0))

print("\nConcatenate v and w (columns):")
print(np.vstack((v,w)).T)

# 7. Concatenate x and v
# This will produce an error because dimensions do not match
# x is 2D (2x2) and v is 1D (2,)
# To concatenate them they must have same dimensions

x + y =
 [[ 6  8]
 [10 13]]

x - y =
 [[-4 -4]
 [-4 -3]]

x * 3 =
 [[ 3  6]
 [ 9 15]]

Square of x:
 [[ 1  4]
 [ 9 25]]

Dot product v·w = 219
Dot product x·v = [29 77]
Dot product x·y =
 [[19 22]
 [50 58]]

Concatenate x and y (rows):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w (columns):
[[ 9 11]
 [10 12]]


In [10]:
#Problem 4: Matrix Operations
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)

print("A inverse:\n", A_inv)

identity = np.dot(A, A_inv)
print("\nA * A^-1 =\n", identity)

# 2. Prove AB != BA
AB = np.dot(A,B)
BA = np.dot(B,A)

print("\nAB =\n", AB)
print("\nBA =\n", BA)

# 3. Prove (AB)^T = B^T A^T
left = np.transpose(AB)
right = np.dot(np.transpose(B), np.transpose(A))

print("\n(AB)^T =\n", left)
print("\nB^T A^T =\n", right)

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

(AB)^T =
 [[23 51]
 [13 29]]

B^T A^T =
 [[23 51]
 [13 29]]


Given equations:

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

Matrix form:

AX = B

In [11]:
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([
    [-1],
    [-3],
    [9]
])

# Inverse method
A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution (x, y, z):\n", X)

Solution (x, y, z):
 [[ 2.]
 [ 1.]
 [-2.]]
